### ISSUE TITLE
Missing cleanup of old configuration files

### ISSUE THREAD

**Issue by artem-sidorenko** [sous-chefs/sysctl#100]
### Cookbook version
0.10.0

### Scenario:
There [was](https://github.com/sous-chefs/sysctl/pull/61) a refactoring in 0.10.0. After this refactoring sysctl cookbook starts to store the sysctl flags to the dedicated files instead of managing a big file.
In the same time there is no cleanup of sysctl files created before. E.g. on RHEL systems you would still have the `99-chef-attributes.conf' together with new files. This can lead to unpredicted results, as the old files are not removed and are not managed anymore.

It would be nice to have a cleanup code in default.rb, which would remove the old files.

**Comment by damacus** [comment]
As we have no real way of tracking the old sysctl files I would recommend writing a file resource to make sure they are deleted. 

I'm going to call this out of scope of this cookbook. Apologies as this isn't probably what you wanted to hear! 👍

**Comment by artem-sidorenko** [comment]
@damacus no problem, we already fixed that on our side with file resource :)

**Comment by damacus** [comment]
Brilliant, glad to hear this hasn't negatively impacted you long term.
