### ISSUE TITLE
1.0.0 unnecessarily(?) breaks existing users

### ISSUE THREAD

**Issue by zts** [sous-chefs/sysctl#111]
### Cookbook version
1.0.0

### Chef-client version
12.x

### Platform Details
Amazon Linux

### Scenario:
Several cookbooks in my environment depend on the sysctl cookbook, each of these contains `include_recipe "sysctl"` before the first use of `sysctl_param`.

The changelog for 1.0.0 notes that "recipes:default no longer needs to be added to persist parameters" - awesome!  However, the default recipe was deleted entirely.  This causes include_recipe to fail, which means that all consumers of this cookbook need to update simultaneously.

I propose adding an empty default recipe to this cookbook to preserve backward compatibility.  Or, if the break was intended, could this be more clearly called out as a breaking change in the release notes?

I'm happy to submit a PR either way, but I'm not sure what the intent was.

**Comment by damacus** [comment]
I'm really sorry but in this case, I would suggest pinning your dependency until you can update your downstream cookbooks. 

This was one of the reasons for the major version bump.
