### ISSUE TITLE
v1.0.0: Params that have not been changed do not get written out to disk

### ISSUE THREAD

**Issue by Poohblah** [sous-chefs/sysctl#112]
Prior to version 1.0.0 of the sysctl cookbook, when setting a sysctl param with the `sysctl_param` resource, [the current value was verified against both `sysctl -n` and the contents of `/etc/sysctl.d`](https://github.com/sous-chefs/sysctl/blob/v0.10.2/libraries/helpers_param.rb#L48).  However, with 1.0.0, [the check against `/etc/sysctl.d` was dropped and the current value is only verified with `sysctl -n`](https://github.com/sous-chefs/sysctl/blob/master/libraries/helpers.rb#L9-L13).  This means that sysctl params that are "accidentally" correct (including params that haven't changed from their default values) will not get persisted.

To give an example: if I the default value of the sysctl param  "foo" is "0", then I set foo to "1" using `sysctl foo=1`, and then I run a cookbook that contains the resource `sysctl_param('foo') { value(1) }`, then the `sysctl_param` resources assumes that the `foo` param has not changed, no file `/etc/sysctl.d/99-chef-foo` will get written out, so the next time the system reboots, `foo` will reset to its default value of "0".

As a user of the sysctl cookbook, I expect the `sysctl_param` resource to guarantee that the value given for the param is persisted, so that the system will always boot up with the correct value applied for the given sysctl param.

**Comment by damacus** [comment]
Any way you can write a test for this case so I understand it a little more? Sounds like you're persisting a default value? In that case, it shouldn't persist a value that's already set. 

My logic for the below may or may not be correct: 

We need to 
- Test a value
- If that value is the same as the one we're setting don't set anything. 
- Action. If it's different

If we don't test and act upon the value we can't get reliable results.

**Comment by Poohblah** [comment]
Yeah I tried to write tests when creating the PR but existing tests seemed to be a bit thin (so I wasn't totally sure if you were actually using tests), I don't use chef delivery, and I don't have much time. So that all just conspired against me.  I can probably write tests but I just have to get over those obstacles first :)

AFAIAC these should be the test cases:

1. * When no `/etc/sysctl.d/99-chef-*` file exists for the param
    * And `sysctl -n` shows that the param is not in the desired state
    * The param resource should be executed

2. * When no `/etc/sysctl.d/99-chef-*` file exists for the param
    * And `sysctl -n` shows that the param is in the desired state
    * The param resource should be executed

3. * When a `/etc/sysctl.d/99-chef-*` file exists for the param
    * And the file contains the correct value
    * And `sysctl -n` shows that the param is not in the desired state
    * The param resource should be executed

4. * When a `/etc/sysctl.d/99-chef-*` file exists for the param
    * And the file contains the correct value
    * And `sysctl -n` shows that the param is in the desired state
    * The param resource should not be executed

5. * When a `/etc/sysctl.d/99-chef-*` file exists for the param
    * And the file does not contain the correct value
    * And `sysctl -n` shows that the param is not in the desired state
    * The param resource should be executed

6. * When a `/etc/sysctl.d/99-chef-*` file exists for the param
    * And the file does not contain the correct value
    * And `sysctl -n` shows that the param is in the desired state
    * The param resource should not be executed

I think 2. may be the contentious one here; I claim that the sysctl.d file should always be created and written out with the correct value since it is the only way to guarantee that a param will persist across a reboot.

**Comment by Poohblah** [comment]
I would argue this is a bug report, not a feature request, since functionality that was present in versions < 1.0.0 is now missing in versions >= 1.0.0.
