### ISSUE TITLE
sysctl attributes in version 1.0.1

### ISSUE THREAD

**Issue by mozulamt** [sous-chefs/sysctl#115]
### Cookbook version
[1.0.1]

### Chef-client version
[12.19.36]

### Platform Details
[physical Ubuntu 14.04.4 LTS kernel version 4.2.0-27-generic]

### Scenario:
We are trying to update from sysctl cookbook 0.10.2 to 1.0.1 but sysctl attributes seem to be ignored.

### Steps to Reproduce:
Attributes file used to work with the following example:
`default['sysctl']['params']['vm']['swappiness'] = 20
default['sysctl']['params']['net']['core']['netdev_max_backlog'] = 50000
default['sysctl']['params']['net']['ipv4']['tcp_fin_timeout'] = 30`

### Expected Result:
and files were populated like:
/etc/sysctl.d/99-chef-vm.swappiness.conf
with 
`vm.swappiness = 20`

### Actual Result:
No new files are created in /etc/sysctl.d/ unless I use the following
`sysctl_param 'vm.swappiness' do`
  `value 20` <- there should be 2 spaces on this line
`end`

in a recipe. Have the attributes changed? Or am I missing something obvious?
The following is in the README
`There are two main ways to interact with the cookbook. This is via chef attributes or via the resource.` 
so I assume I can still use attributes to populate /etc/sysctl.d/ - correct?

**Comment by damacus** [comment]
That's correct, as per the usage section in the readme https://github.com/sous-chefs/sysctl#usage 

We don't use attributes.
