### ISSUE TITLE
Undefined method `new_resource` for Custom resource sysctl_param from cookbook sysctl

### ISSUE THREAD

**Issue by furbiesandbeans** [sous-chefs/sysctl#119]
### Cookbook version
1.0.1

### Chef-client version
12.6.0

### Platform Details
Ubuntu 14.04

### Scenario:
Disable swapiness

### Steps to Reproduce:
Set the following inside a recipe:
sysctl_param 'vm.swappiness' do
  value 0
end

### Expected Result:
Swapiness set to 0, no errors

### Actual Result:
           ================================================================================
           Error executing action `apply` on resource 'sysctl_param[vm.swappiness]'
           ================================================================================
           
           NoMethodError
           -------------
           undefined method `new_resource' for Custom resource sysctl_param from cookbook sysctl
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/sysctl/libraries/helpers.rb:5:in `set_sysctl_param'
           /tmp/kitchen/cache/cookbooks/sysctl/resources/param.rb:56:in `block (2 levels) in class_from_file'
           /tmp/kitchen/cache/cookbooks/sysctl/resources/param.rb:46:in `block in class_from_file'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/verifi_mysql/recipes/files.rb
           
            58: sysctl_param 'vm.swappiness' do
            59:   value 20
            60: end
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/verifi_mysql/recipes/files.rb:58:in `from_file'
           
           sysctl_param("vm.swappiness") do
             action [:apply]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :sysctl_param
             cookbook_name "verifi_mysql"
             recipe_name "files"
             value "20"
             key "vm.swappiness"
             conf_dir "/etc/sysctl.d"
           end

**Comment by damacus** [comment]
Are you able to try it on a newer version of the chef-client? We may need to up the chef-version requirements... 


Thanks!

**Comment by furbiesandbeans** [comment]
In our org, we run into other issues when we try to up the chef version. For right now, I won't be able to test. Thanks for looking into the issue, you might want to update your README since it says it works on chef versions 12.5+

**Comment by damacus** [comment]
It's actually in the metadata.rb file. 

Given chef-client 12 is [going EOL in April](https://www.chef.io/eol-chef12-and-chefdk1/) I may just bump the chef-client version up to 13+.

Closing for now. If you happen to find which version is works on drop us a line and we'll update the README and metadata.rb

**Comment by furbiesandbeans** [comment]
Well, we know it doesnt work with 12.6 lol. Both metadata.rb and README specify 12.5+, doesnt make sense... The current requirements should change.
