### ISSUE TITLE
Ability to change notify for service[procps]

### ISSUE THREAD

**Issue by vills** [sous-chefs/sysctl#34]
Sometimes notifying service[procps] to start doesn't apply sysctl params, because when service[procps] started, some modules can be not loaded still.
It would be nice to see something like attribute to change behavior here: https://github.com/svanzoest-cookbooks/sysctl/blob/master/recipes/default.rb#L57

**Comment by svanzoest** [comment]
Do you have an example that we can code up as one of the tests and make sure we handle that or come up with a recommendation?

**Comment by vills** [comment]
I found it on conntrack parameters, for example.

**Comment by svanzoest** [comment]
@vills do you have a test that reproduces the issue? I have made changes with conntrack parameters all the time, so it would be helpful to see a coded example.

**Comment by vills** [comment]
@svanzoest for example on ubuntu-14.04:

```
root@conntrack:~# sysctl -a | grep conntrack
kernel.hostname = conntrack

root@conntrack:~# modprobe nf_conntrack

root@conntrack:~# sysctl -a | grep conntrack
kernel.hostname = conntrack
net.netfilter.nf_conntrack_acct = 0
net.netfilter.nf_conntrack_buckets = 8192
net.netfilter.nf_conntrack_checksum = 1
net.netfilter.nf_conntrack_count = 0
net.netfilter.nf_conntrack_events = 1
net.netfilter.nf_conntrack_events_retry_timeout = 15
net.netfilter.nf_conntrack_expect_max = 124
net.netfilter.nf_conntrack_generic_timeout = 600
net.netfilter.nf_conntrack_helper = 1
net.netfilter.nf_conntrack_log_invalid = 0
net.netfilter.nf_conntrack_max = 31808
net.netfilter.nf_conntrack_timestamp = 0
net.nf_conntrack_max = 31808
```

So, problem appear, when module *nf_conntrack* isn't loaded in kernel and you tries configure those sysctl parameters.

**Comment by fhanson** [comment]
I am seeing similar behavior on CentOS for 6.6 and 6.7.  Conntrack only gets loaded on future chef runs or on reboot.

**Comment by svanzoest** [comment]
This seems like a timing issue. I would assume you define the kernel module
earlier in the chef run?

**Comment by fhanson** [comment]
Must be a different issue after all, I can reliably load the default conntrack values but new values set by attributes are not set until after reboot.

**Comment by vills** [comment]
@svanzoest we use cookbook 'iptables-ng' for example. It loads all needed modules, but at the end of chef-run (delayed).
And cookbook[sysctl] appears in run_list after cookbook[iptables-ng].

**Comment by svanzoest** [comment]
the sysctl cookbook will apply them at the time the cookbook is run as you want those change to take into effect immediately. This is in conflict with loading the modules delayed. you can make the same call as what `sysctl::apply` does, but `delayed` rather then calling it explictly, or have the kernel modules applied before the sysctl cookbook runs.

**Comment by axelrtgs** [comment]
Was just following up on issues and PRs and giving some attention to the sysctl cookbook and was wondering if this was still relevant since its over a years old or if its been addressed sometime in between and the issue is just lingering. From what i gathered in my limited context this issue was due to the module being loaded later in the chef run and not being able to apply the values before the module was loaded. did the comment above help resolve the issue?
