### ISSUE TITLE
node['sysctl']['allow_sysctl_conf'] and pre-existing conf files

### ISSUE THREAD

**Issue by dpetzel** [sous-chefs/sysctl#49]
I have a situation where our base Centos 7 image (which is outside of my control) has a pre-existing `/etc/sysctl.conf`

I'm attempting to use this cookbook, and I'm using the default value for `node['sysctl']['allow_sysctl_conf']` of `false`.

When I run the cookbook, a new file (`/etc/sysctl.d/99-chef-attributes.conf`) is created with the value I set.

The problem is that in that pre-existing file, the key I am setting already exists with a different value,  and it appears that `systemd-sysctl.service` prefers that file over the `/etc/sysctl.d/` one. Based on `man sysctl.conf` it seems the load order is:

```
       /run/sysctl.d/*.conf
       /etc/sysctl.d/*.conf
       /usr/local/lib/sysctl.d/*.conf
       /usr/lib/sysctl.d/*.conf
       /lib/sysctl.d/*.conf
       /etc/sysctl.conf
```

This lines up with what I am seeing getting set.

I understand that in a wrapper I **could** wipe out that pre-existing configuration file, but I'm raising the question here on if `node['sysctl']['allow_sysctl_conf']` set to `false` should blow that pre-existing file away. As-is it is a little confusing to tell the system not to allow that file, yet its present and preferred over custom files.

**Comment by axelrtgs** [comment]
Hello @dpetzel This issue has been open for a while with a pending question, i was wondering if you still had questions regarding this behavior or if the issue/question was no longer relevant?

**Comment by axelrtgs** [comment]
As a potential solution if this was still not resolved and given your use case of overwriting /etc/sysctl.conf can you try setting node['sysctl']['allow_sysctl_conf'] to true which according to the readme of the latest version should overwrite that file instead of using the confdir and should achieve the result you are after if i understood correctly.

> node['sysctl']['allow_sysctl_conf'] - Defaults to false. Using conf_dir is highly recommended. On some platforms that is not supported. For those platforms, set this to true and the cookbook will rewrite the /etc/sysctl.conf file directly with the params provided. Be sure to save any local edits of /etc/sysctl.conf before enabling this to avoid losing them.
