### ISSUE TITLE
Old 99-chef-attributes.conf is replaced when setting a new config param

### ISSUE THREAD

**Issue by manojVivek** [sous-chefs/sysctl#62]
The apply action of the param when called for the second run with a new param, is replacing the already created 99-chef-attributes.conf file. Thus resulting in the loss of the already configured params.
Shouldn't it be appending the new params to the old file instead of replacing it?

**Comment by svanzoest** [comment]
the cookbook will replace the `99-chef-attributes.conf` file with all the persisted attributes according to chef. It basically configures it with the attributes that chef is aware of and replaces what was there before. This also means you can now reset parameters to the OS default.

If you `apply` a `sysctl_param` it needs to be applied at every chef run. Are you seeing a scenario where this not the behavior?

**Comment by axelrtgs** [comment]
Hello @manojVivek This issue has been open for a while with a pending question, i was wondering if you still had questions regarding this behavior or if the answer above was adequate enough and the issue can be closed.

**Comment by manojVivek** [comment]
@axelrtgs The previous reply is sufficient, we can close this. Thanks!
