### ISSUE TITLE
Support for amazon platform.

### ISSUE THREAD

**Issue by ff-jantreassian** [sous-chefs/sysctl#85]
### Cookbook version
0.9.0

### Chef-client version
13.0.118

### Platform Details
platform=amazon
           platform_version=2017.03
           ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

### Scenario:
Trying to run a recipe that contains 

> include_recipe 'sysctl::default' 
in order to use sysctl_param resource

### Steps to Reproduce:
Run a recipe that includes sysctl cookbook on the amazon platform

### Expected Result:
Expecting a successful converge.

### Actual Result:
`       
Recipe: sysctl::service
         * template[/etc/rc.d/init.d/procps] action create (skipped due to only_if)
         * service[procps] action enable
           * service[procps]: Service is not known to chkconfig.
           ================================================================================
           Error executing action 'enable' on resource 'service[procps]'
           ================================================================================

           Chef::Exceptions::Service
           -------------------------
           service[procps]: Service is not known to chkconfig.

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/sysctl/recipes/service.rb

            26: service 'procps' do
            27:   supports :restart => true, :reload => true, :status => false
            28:   action :enable
            29: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/sysctl/recipes/service.rb:26:in 'from_file'

           service("procps") do
             action [:enable]
             default_guard_interpreter :default
             service_name "procps"
             enabled nil
             running nil
             masked nil
             pattern "procps"
             declared_type :service
             cookbook_name "sysctl"
             recipe_name "service"
             supports {:restart=>true, :reload=>true, :status=>false}
           end
`

**Comment by ff-jantreassian** [comment]
The strange thing about this issue is that the amazon platform's platform_family is rhel.
I see that rhel is listed on the guard in services.rb

**Comment by svanzoest** [comment]
In chef 13 Amazon platform_family is `amazon`, which is likely the reason.

**Comment by ff-jantreassian** [comment]
Thanks @svanzoest,
Can I submit a pull request? or do you think you can have 0.9.2 to support platform_family amazon soon? :)

**Comment by axelrtgs** [comment]
@ff-jantreassian If you have a pull request that fixes this please feel free to submit. I do not have experience with amazon but i can see if i can figure out enough to fix and test this if you are not able to submit a PR

**Comment by tas50** [comment]
This is fixed by https://github.com/sous-chefs/sysctl/pull/91

**Comment by axelrtgs** [comment]
#91 with support for amazon linux and other fixes was merged. Thank you for your contribution it is appreciated.
