### ISSUE TITLE
Feature Request:  Specify conf file

### ISSUE THREAD

**Issue by donwlewis** [sous-chefs/sysctl#89]
Was thinking that it would be nice to be able to specify the conf file name to be used, that way you can leverage multiple files say if you wanted to separate your hardening parameters vs your application tuning parameters.  I will try to submit a pull request for this feature if I have time, but if someone gets to it first, be my guest.

**Comment by donwlewis** [comment]
So I guess I am wrong on this one.  Looks like if you set `node['sysctl']['conf_file']` to something, it will write the config there.  Good to know.  Maybe we could ad this as a parameter to the LWRP resource.  Also noticed that the LWRP resources seems to apply the changes each time the chef client runs.

**Comment by damacus** [comment]
I'm going to amalgamate this into #104
