### ISSUE TITLE
does not combine sysctl files for version higher than 0.9.0

### ISSUE THREAD

**Issue by y0y0z** [sous-chefs/sysctl#97]
### Cookbook version
0.10.1

### Scenario:
`attributes/default.rb` file is missing since version 0.10.0, which [exists on previous versions](https://github.com/sous-chefs/sysctl/blob/v0.9.0/attributes/default.rb)

### Scenario:
using version higher than 0.9.0 does not [combine sysctl files](https://github.com/sous-chefs/sysctl/blob/master/libraries/sysctl_param.rb#L56)

### Expected Result:
to combine sysctl files into a single file

### Actual Result:
does not combine sysctl files into a single file

**Comment by hulu1522** [comment]
We are having the same issue.  We cannot go past 0.9.0 because it keeps failing.

```
================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/nfs/attributes/default.rb
================================================================================

Chef::Exceptions::AttributeNotFound
-----------------------------------
could not find filename for attribute default in cookbook sysctl

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:389:in `resolve_attribute'
  /var/chef/cache/cookbooks/nfs/attributes/default.rb:20:in `from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:

382:      # @raise [Chef::Exceptions::AttributeNotFound] If the attribute file could not be found.
383:      #
384:      def resolve_attribute(cookbook_name, attr_file_name)
385:        cookbook = cookbook_collection[cookbook_name]
386:        raise Chef::Exceptions::CookbookNotFound, "could not find cookbook #{cookbook_name} while loading attribute #{name}" unless cookbook
387:  
388:        attribute_filename = cookbook.attribute_filenames_by_short_filename[attr_file_name]
389>>       raise Chef::Exceptions::AttributeNotFound, "could not find filename for attribute #{attr_file_name} in cookbook #{cookbook_name}" unless attribute_filename
390:  
391:        attribute_filename
392:      end
393:  
394:      #
395:      # A list of all recipes that have been loaded.
396:      #
397:      # This is stored internally as a Hash, so ordering is predictable.
398:      #

Platform:
---------
x86_64-linux


Running handlers:
Running handlers complete
Chef Client failed. 0 resources updated in 06 seconds
```

**Comment by y0y0z** [comment]
@damacus: i would be happy to help you in anyway i can, though i do not have any development and testing environment. how do you think i could help?

**Comment by damacus** [comment]
Hey @y0y0z we can do one of two things (or both). 

- Revert the removal of attributes/default.rb 
- Ignore the breaking change and look at moving to the long term goal of making custom resources work.

**Comment by y0y0z** [comment]
@damacus: i do not have any development environment. i can fork, do the modifications, push the changes, and submit a pull-request. though, i cannot clone the repository on my local machine. to address your first bullet, i think executing `git checkout bd9cc0f attributes/default.rb` should do the trick. yet, i am unsure whether it will resolve the issue as i have no way of testing it.

sorry i couldn't do more right now :(

**Comment by damacus** [comment]
Do you have a copy of ChefDK + vagrant + virtualbox or something similar?

**Comment by y0y0z** [comment]
@damacus: if i had it, i would have create pull request

**Comment by y0y0z** [comment]
my version is still locked on 0.9.0

**Comment by damacus** [comment]
Hi @y0y0z you can get a copy of [ChefDK here](https://downloads.chef.io/chefdk/current) and [VirtualBox here](https://www.virtualbox.org/wiki/Downloads).

This should help you get started. 

In the meantime I'm going to close this. As I'm about to do a refactor to custom resources. 

Thanks! 
Dan
